"use client"

import Head from "next/head"
import { Inter } from "next/font/google"
import Layout from "../components/Layout"
import Image from "next/image"
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from "../components/AnimatedText"
import Link from "next/link"
const inter = Inter({ subsets: ["latin"] })
import { LinkArrow } from "../components/Icons"
import HireMe from "../components/HireMe"
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import { useEffect, useState } from "react"
import TransitionEffect from "../components/TransitionEffect"

export default function Home() {
  const [isMobile, setIsMobile] = useState(false)

  useEffect(() => {
    // Check if window is defined (browser environment)
    if (typeof window !== "undefined") {
      const handleResize = () => {
        setIsMobile(window.innerWidth < 768)
      }

      // Set initial value
      handleResize()

      // Add event listener
      window.addEventListener("resize", handleResize)

      // Clean up
      return () => window.removeEventListener("resize", handleResize)
    }
  }, [])

  return (
    <>
      <Head>
        <title>create next app</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen pt-0">
      {isMobile ? (
          // Mobile Layout
          <div className="w-full px-0 pt-0">
            <div className="flex flex-col items-center mt-0">
              {/* Profile Image */}
              <div className="w-full max-w-md mx-auto mb-2">
                <Image 
                  src={profilePic || "/placeholder.svg"} 
                  alt="codeBucks" 
                  className="w-full h-auto"
                  priority 
                />
              </div>

              {/* Heading */}
              <h1 className="text-4xl font-bold text-center mb-2 px-4 leading-tight">
                Turning Vision Into Reality With Code And Design.
              </h1>

              {/* Paragraph */}
              <p className="text-base font-medium text-center mb-4 px-8 max-w-lg mx-auto">
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>

              {/* Buttons */}
              <div className="flex items-center justify-center space-x-6 mb-6">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center bg-black text-white p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-gray-300 hover:text-black
                  border-2 border-solid border-transparent hover:border-gray-700"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:gokulakrishnan.msamy@gmail.com"
                  target={"_blank"}
                  className="text-lg font-medium capitalize text-dark underline"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        ) : (
          // Desktop Layout
          <Layout className="pt-0 p-0 md:p-8">
            <div className="flex items-center justify-between w-full -mt-16">
              <div className="w-1/2 -mt-8">
                <Image 
                  src={profilePic || "/placeholder.svg"} 
                  alt="codeBucks" 
                  className="w-full h-auto"
                  priority 
                />
              </div>
              <div className="w-1/2 flex flex-col items-center self-center">
                <AnimatedText
                  text="Turning Vision Into Reality With Code And Design."
                  className="!text-6xl !text-left"
                />
                <p className="my-4 text-base font-medium">
                  As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
                  Explore my latest projects and articles, showcasing my expertise in React.js and web development.
                </p>
                <div className="flex items-center self-start mt-2">
                  <Link
                    href="/dummy.pdf"
                    target={"_blank"}
                    className="flex items-center bg-black text-white p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-gray-300 hover:text-black
                  border-2 border-solid border-transparent hover:border-gray-700"
                    download={true}
                  >
                    Resume <LinkArrow className={"w-6 ml-1"} />
                  </Link>
                  <Link
                    href="mailto:gokulakrishnan.dev@gmail.com"
                    target={"_blank"}
                    className="ml-4 text-lg font-medium capitalize text-dark underline"
                  >
                    Contact
                  </Link>
                </div>
              </div>
            </div>
          </Layout>
        )}

        {!isMobile && <HireMe />}

        {!isMobile && (
          <div className="absolute right-8 bottom-8 inline-block w-24">
            <Image src={lightBulb || "/placeholder.svg"} alt="codeBucks" className="w-full h-auto" />
          </div>
        )}
      </main>
    </>
  )
}
